import pymysql
import chromadb

from langchain_core.tools import tool
from ultralytics import YOLO
from sentence_transformers import SentenceTransformer

def get_db_connection():
    return pymysql.connect(
        host='mysql',
        user='sail',
        password='password',
        database='laravel',
        cursorclass=pymysql.cursors.DictCursor
    )

@tool
def get_inventory(product_name: str) -> dict:
    """
    Query the product inventory, price, and active status from the database.
    Use this tool when the user asks about the stock, inventory, quantity, or price of a specific product.
    
    Args:
        product_name: The exact name of the product to search for (e.g., "Dutch Lady").
    """
    try:
        connection = get_db_connection()
        with connection.cursor() as cursor:
            sql = """
                SELECT name, stock_quantity, price, is_active 
                FROM products 
                WHERE name LIKE %s 
                LIMIT 1
            """

            cursor.execute(sql, (f"%{product_name}%",))
            result = cursor.fetchone()
            
        connection.close()
        
        if result:
            return {
                "product": result["name"],
                "stock": result["stock_quantity"],
                "price": float(result["price"]), 
                "status": "In Stock" if result["stock_quantity"] > 0 else "Out of Stock",
                "is_active": "Active" if result["is_active"] else "Discontinued"
            }
        else:
            return {"error": f"I couldn't find any product matching '{product_name}' in our database."}
            
    except Exception as e:
        return {"error": f"Database query failed: {str(e)}"}
    

# ------------------------------------------------
# YOLO Vision Tool
# ------------------------------------------------
vision_model = YOLO("best.pt")

@tool
def analyze_product_image(image_path: str) -> str:
    """
    Use this tool to analyze an image and detect what products are in it.
    Call this tool ONLY WHEN the user provides an image and asks you to look at it or scan it.
    
    Args:
        image_path: The file path to the image that needs to be analyzed.
    """
    try:
        results = vision_model(image_path, conf=0.5)
        detected_names = []
        
        # extract the detected class names
        for box in results[0].boxes:
            cls_id = int(box.cls[0])
            name = vision_model.names[cls_id]
            detected_names.append(name)
            
        if not detected_names:
            return "No known products were detected in this image."
            
        # remove duplicates by converting to a set and then back to a list
        unique_products = list(set(detected_names))
        return ", ".join(unique_products)
        
    except Exception as e:
        return f"Error analyzing the image: {str(e)}"
    

# ------------------------------------------------
# RAG model for product knowledge retrieval
# ------------------------------------------------
rag_embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
chroma_client = chromadb.PersistentClient(path="/app/chroma_data")
knowledge_collection = chroma_client.get_or_create_collection(name="product_knowledge")

@tool
def get_product_knowledge(query: str) -> str:
    """
    Query the product knowledge base for non-structured details like ingredients, 
    health benefits, storage instructions, return policies, and target audience.
    
    Use this tool when the user asks specific questions about product features, 
    suitability, or usage. Do NOT use this for real-time price or stock.
    
    Args:
        query: The semantic question asked by the user (e.g., "Is there any drink good for gym people?").
    """
    try:
        # 1. Convert the query generated by the large model into a vector
        query_vector = rag_embedding_model.encode(query).tolist()
        
        # 2. Query the ChromaDB collection for the most relevant product knowledge based on the query vector
        results = knowledge_collection.query(
            query_embeddings=[query_vector],
            n_results=2
        )
        
        # 3. Parse the results and return them to the large model
        if results and results['documents'] and results['documents'][0]:
            retrieved_docs = results['documents'][0]
            # Merge the most relevant documents into a single text string, to be passed to the large model as factual evidence (Grounding)
            return "\n\n".join(retrieved_docs)
        else:
            return "I couldn't find any relevant product knowledge for this query."
            
    except Exception as e:
        return f"Error retrieving product knowledge: {str(e)}"
    


# put all tools into a list for easy integrate to the model
tools_list = [get_inventory, analyze_product_image, get_product_knowledge]